const fs = require('fs');

const approvedProducts = `    // Flagship Curated 19-Product Catalog (Strictly Approved Items + Nomad Bundle)
    const PRODUCTS = {
      p1: {
        id: 'p1',
        name: 'MagFold™ 3-in-1 Foldable Charger',
        category: 'power',
        badge: 'Flagship Bestseller',
        badgeColor: 'bg-zinc-800',
        price: 34.99,
        originalPrice: 69.99,
        wholesale: 10.50,
        rating: 4.9,
        reviews: 842,
        image: 'magfold_hero.jpg',
        fallback: 'magfold_hero.jpg',
        desc: 'Origami fold charging station for iPhone (15W), Apple Watch, and AirPods simultaneously.'
      },
      p2: {
        id: 'p2',
        name: 'Volt65™ 65W GaN Travel Fast Charger',
        category: 'power',
        badge: 'GaN III Fast',
        badgeColor: 'bg-zinc-800',
        price: 24.99,
        originalPrice: 39.99,
        wholesale: 6.20,
        rating: 4.8,
        reviews: 418,
        image: 'volt65_gan.jpg',
        fallback: 'volt65_gan.jpg',
        desc: 'Dual USB-C PD fast power block. Powers MacBook Air, MagFold, and iPad at full wattage.'
      },
      p3: {
        id: 'p3',
        name: 'MagStand™ Slim Leather Wallet & Kickstand',
        category: 'magsafe',
        badge: 'MagSafe Leather',
        badgeColor: 'bg-zinc-800',
        price: 19.99,
        originalPrice: 34.99,
        wholesale: 3.40,
        rating: 4.9,
        reviews: 654,
        image: 'magstand_wallet.jpg',
        fallback: 'magstand_wallet.jpg',
        desc: 'Magnetic vegan leather wallet. Snaps to iPhone, holds 3 cards, and folds into portrait/landscape stand.'
      },
      p4: {
        id: 'p4',
        name: 'MagPower™ 10,000mAh Magnetic Powerbank',
        category: 'power',
        badge: 'Viral TikTok',
        badgeColor: 'bg-zinc-800',
        price: 39.99,
        originalPrice: 69.99,
        wholesale: 12.80,
        rating: 4.9,
        reviews: 912,
        image: 'magpower_powerbank.jpg',
        fallback: 'magpower_powerbank.jpg',
        desc: 'Strong snap magnetic battery pack with digital LED display and foldable zinc alloy kickstand.'
      },
      p5: {
        id: 'p5',
        name: 'NomadCube™ 100W 4-Port GaN Desktop Hub',
        category: 'power',
        badge: 'Pro Station',
        badgeColor: 'bg-zinc-800',
        price: 49.99,
        originalPrice: 89.99,
        wholesale: 15.00,
        rating: 4.9,
        reviews: 524,
        image: 'nomadcube_hub.jpg',
        fallback: 'nomadcube_hub.jpg',
        desc: 'Heavy-duty 100W GaN charging hub with 3x USB-C PD and 1x USB-A. Fast-charges 2 MacBooks at once.'
      },
      p6: {
        id: 'p6',
        name: 'OrbitDock™ 360 Magnetic Floating iPad Stand',
        category: 'magsafe',
        badge: 'Studio Pick',
        badgeColor: 'bg-zinc-800',
        price: 44.99,
        originalPrice: 79.99,
        wholesale: 14.20,
        rating: 4.9,
        reviews: 431,
        image: 'orbitdock_ipad.jpg',
        fallback: 'orbitdock_ipad.jpg',
        desc: 'Aerospace aluminum rotating stand for iPad Pro/Air with strong neodymium magnetic alignment.'
      },
      p7: {
        id: 'p7',
        name: 'AeroRise™ Ergonomic Aluminum MacBook Riser',
        category: 'desk',
        badge: 'Ergonomic Pro',
        badgeColor: 'bg-zinc-800',
        price: 34.99,
        originalPrice: 59.99,
        wholesale: 9.80,
        rating: 4.9,
        reviews: 388,
        image: 'stand_1.jpg',
        fallback: 'stand_1.jpg',
        desc: 'CNC-machined aluminum MacBook riser with thermal cooling ventilation and eye-level ergonomic tilt.'
      },
      p8: {
        id: 'p8',
        name: 'GaNStream™ 140W PD 3.1 Ultra-Fast Charger',
        category: 'power',
        badge: 'Max Power',
        badgeColor: 'bg-zinc-800',
        price: 64.99,
        originalPrice: 109.99,
        wholesale: 21.00,
        rating: 4.9,
        reviews: 320,
        image: 'ganstream_charger.jpg',
        fallback: 'ganstream_charger.jpg',
        desc: 'Next-gen PD 3.1 28V/5A charging brick. Fast-charges 16\" MacBook Pro to 50% in 28 minutes.'
      },
      p9: {
        id: 'p9',
        name: 'StudioMat™ Waterproof Vegan Leather Desk Pad (90x40cm)',
        category: 'desk',
        badge: 'Clean Desk',
        badgeColor: 'bg-zinc-800',
        price: 22.99,
        originalPrice: 39.99,
        wholesale: 5.50,
        rating: 4.8,
        reviews: 392,
        image: 'studiomat_deskpad.jpg',
        fallback: 'studiomat_deskpad.jpg',
        desc: 'Dual-sided waterproof vegan leather mat. Spills wipe clean instantly, provides flawless optical glide.'
      },
      p10: {
        id: 'p10',
        name: 'TitanLink™ Titanium Magnetic Apple Watch Band',
        category: 'magsafe',
        badge: 'Grade 2 Titanium',
        badgeColor: 'bg-zinc-800',
        price: 39.99,
        originalPrice: 69.99,
        wholesale: 8.50,
        rating: 4.9,
        reviews: 512,
        image: 'titanlink_watch_band.jpg',
        fallback: 'titanlink_watch_band.jpg',
        desc: 'Aerospace Grade 2 titanium link strap with scratch-resistant DLC coating and magnetic clasp for Apple Watch.'
      },
      p11: {
        id: 'p11',
        name: 'PrismBeam™ Architectural Matte Studio Desk Lamp',
        category: 'desk',
        badge: 'Studio Lighting',
        badgeColor: 'bg-zinc-800',
        price: 42.99,
        originalPrice: 79.99,
        wholesale: 12.50,
        rating: 4.8,
        reviews: 274,
        image: 'prismbeam_desk_lamp.jpg',
        fallback: 'prismbeam_desk_lamp.jpg',
        desc: 'Minimalist architectural matte black studio desk lamp with touch-dimming warm glow and eye-care diffuser.'
      },
      p12: {
        id: 'p12',
        name: 'AeroBridge™ Solid Wood & Aluminum Monitor Riser Shelf',
        category: 'desk',
        badge: 'Workspace Shelf',
        badgeColor: 'bg-zinc-800',
        price: 54.99,
        originalPrice: 94.99,
        wholesale: 16.00,
        rating: 4.9,
        reviews: 419,
        image: 'aerobridge_monitor_riser.jpg',
        fallback: 'aerobridge_monitor_riser.jpg',
        desc: 'Elevated dual-monitor desk shelf riser with anodized aluminum legs to slide keyboard and accessories underneath.'
      },
      p13: {
        id: 'p13',
        name: 'StudioAcoustic™ Hi-Fi Over-Ear Headphones',
        category: 'audio',
        badge: 'Audiophile Sound',
        badgeColor: 'bg-zinc-800',
        price: 59.99,
        originalPrice: 119.99,
        wholesale: 18.00,
        rating: 4.9,
        reviews: 618,
        image: 'aircushion_headphone_stand.jpg',
        fallback: 'aircushion_headphone_stand.jpg',
        desc: 'Audiophile closed-back over-ear headphones with plush memory foam ear cushions and braided detachable cable.'
      },
      p14: {
        id: 'p14',
        name: 'AeroArmor™ Frosted MagSafe iPhone Protective Case',
        category: 'magsafe',
        badge: 'MagSafe Armor',
        badgeColor: 'bg-zinc-800',
        price: 18.99,
        originalPrice: 34.99,
        wholesale: 3.50,
        rating: 4.8,
        reviews: 580,
        image: 'real_phone_case.jpg',
        fallback: 'real_phone_case.jpg',
        desc: 'Ultra-slim shockproof protective case featuring an integrated MagSafe magnetic alignment ring and anti-scratch matte frosted back.'
      },
      p15: {
        id: 'p15',
        name: 'OrbitShield™ Rugged Aluminum Case for AirPods Pro',
        category: 'audio',
        badge: 'AirPods Pro 2',
        badgeColor: 'bg-zinc-800',
        price: 21.99,
        originalPrice: 38.99,
        wholesale: 4.80,
        rating: 4.8,
        reviews: 342,
        image: 'orbitshield_airpods_case.jpg',
        fallback: 'orbitshield_airpods_case.jpg',
        desc: 'CNC anodized aluminum rugged bumper case with magnetic latch lock and carabiner clip for AirPods Pro 2.'
      },
      p16: {
        id: 'p16',
        name: 'ExecutiveHeritage™ Handcrafted Leather Bi-Fold Wallet',
        category: 'magsafe',
        badge: 'Handcrafted Leather',
        badgeColor: 'bg-zinc-800',
        price: 24.99,
        originalPrice: 49.99,
        wholesale: 5.50,
        rating: 4.9,
        reviews: 488,
        image: 'real_leather_bifold_wallet.jpg',
        fallback: 'real_leather_bifold_wallet.jpg',
        desc: 'Handcrafted genuine top-grain leather bi-fold wallet featuring precision edge stitching, multi-card organizing slots, and a full-length cash compartment.'
      },
      p17: {
        id: 'p17',
        name: 'ExecutiveLeather™ Minimalist Front-Pocket Cardholder',
        category: 'magsafe',
        badge: 'Slim Cardholder',
        badgeColor: 'bg-zinc-800',
        price: 19.99,
        originalPrice: 34.99,
        wholesale: 3.80,
        rating: 4.8,
        reviews: 310,
        image: 'pocketsafe_metal_wallet.jpg',
        fallback: 'pocketsafe_metal_wallet.jpg',
        desc: 'Slim front-pocket genuine leather cardholder wallet with quick thumb-slide card access.'
      },
      p18: {
        id: 'p18',
        name: 'AlignDock™ Vertical Dual MacBook Stand',
        category: 'desk',
        badge: 'Dual Dock',
        badgeColor: 'bg-zinc-800',
        price: 29.99,
        originalPrice: 49.99,
        wholesale: 7.80,
        rating: 4.9,
        reviews: 440,
        image: 'aligndock_vertical_stand.jpg',
        fallback: 'aligndock_vertical_stand.jpg',
        desc: 'Solid weighted aluminum vertical dual-slot dock to store MacBook and iPad upright in clamshell mode.'
      },
      bundle: {
        id: 'bundle',
        name: 'The Ultimate Nomad Travel Bundle (All-in-One)',
        category: 'power',
        badge: '50% OFF BUNDLE',
        badgeColor: 'bg-zinc-800',
        price: 59.99,
        originalPrice: 124.97,
        wholesale: 20.10,
        rating: 5.0,
        reviews: 1240,
        image: 'magfold_hero.jpg',
        fallback: 'magfold_hero.jpg',
        desc: 'Complete travel setup: MagFold 3-in-1 Foldable Charger + Volt65 65W GaN Charger + MagStand Leather Wallet in one box.'
      }
    };

    // Treasury Wallets (Ezana Takele)
    const WALLETS`;

let code = fs.readFileSync('c:/Users/lenovo/Desktop/foldtech-studio/index.html', 'utf8');
code = code.replace(/const PRODUCTS = \{[\s\S]*?const WALLETS/, approvedProducts);

fs.writeFileSync('c:/Users/lenovo/Desktop/foldtech-studio/index.html', code, 'utf8');
fs.writeFileSync('c:/Users/lenovo/Desktop/assessment/docs/index.html', code, 'utf8');
fs.writeFileSync('c:/Users/lenovo/Desktop/assessment/index.html', code, 'utf8');

console.log('SUCCESS: Injected strictly approved products and bundle into all repositories.');
